// vue-todo-list/src/App.vue
<script setup lang="ts">
import { ref, useTemplateRef } from "vue";
import TodoList from "./components/TodoList.vue";

export interface Todo {
  content: string;
}

const todos = ref<Todo[]>([]);

const todoInputRef = useTemplateRef("todo-input-ref");

function handleSubmit(e: Event): void {
  e.preventDefault();

  const todoInputVal = (todoInputRef.value as HTMLInputElement).value;
  if (todoInputVal.trim().length <= 0) return;

  addTodo(todoInputVal);
  (todoInputRef.value as HTMLInputElement).value = "";
}

function addTodo(content: string): void {
  const newTodo = { content };
  todos.value.push(newTodo);
}
</script>

<template>
  <div class="flex h-screen flex-col items-center bg-gray-500 text-center">
    <div class="h-full pt-[30vh]">
      <h1 class="text-2xl">Vue Todo List</h1>
      <form class="my-4 flex justify-center gap-4" v-on:submit="handleSubmit">
        <input class="bg-white p-1" type="text" ref="todo-input-ref" />
        <button class="bg-indigo-400 px-2 hover:bg-indigo-500">Add Todo</button>
      </form>
      <TodoList :todos="todos" @update-todos="todos = $event" />
    </div>
  </div>
</template>

// svelte-todo-list/src/App.svelte
<script lang="ts" module>
  import Todos from "./lib/Todos.svelte";

  let todoInput: HTMLInputElement | null = null;

  export interface Todo {
    content: string;
  }

  let todos = $state<Todo[]>([]);

  function addTodo(e: Event): void {
    e.preventDefault();

    if (todoInput!.value.trim().length <= 0) return;

    todos.push({ content: todoInput!.value });

    todoInput!.value = "";
  }
</script>

<main class="flex h-screen justify-center bg-gray-500">
  <div class="flex flex-col gap-4 text-center">
    <h1 class="mt-40 text-3xl">Svelte Todo List</h1>
    <form>
      <input
        class="bg-white p-1 text-black"
        id="todo-input"
        type="text"
        placeholder="Enter your todo text"
        bind:this={todoInput}
      />
      <button
        class="bg-orange-400 hover:bg-orange-500"
        type="submit"
        onclick={addTodo}
      >
        Add Todo
      </button>
    </form>
    <Todos {todos} />
  </div>
</main>
