// vue-todo-list/src/components/TodoList.vue
<script setup lang="ts">
import type { Todo } from "../App.vue";

const props = defineProps<{ todos: Todo[] }>();
const emit = defineEmits(["updateTodos"]);

function deleteTodo(targetTodo: Todo): void {
  const newTodos = props.todos.filter((todo) => todo !== targetTodo);
  emit("updateTodos", newTodos);
}
</script>

<template>
  <div class="grid gap-2">
    <div
      class="flex w-80 items-center justify-between gap-2 rounded-md bg-white p-2"
      v-for="(todo, index) in todos"
      :key="todo.content + index"
    >
      <span class="text-start break-all">{{ todo.content }}</span>
      <button
        class="max-h-fit self-start bg-red-500 p-1 whitespace-nowrap hover:bg-red-600"
        v-on:click="deleteTodo(todo)"
      >
        Delete Todo
      </button>
    </div>
  </div>
</template>

// redux-todo-list/src/components/TodoList.tsx
import { useSelector } from "react-redux";
import type { Todo } from "../app/App";
import { deleteTodo, store, type RootState } from "../store/store";

export function TodoList() {
  const todos = useSelector((state: RootState) => state.todos);

  function handleClick(targetTodo: Todo): void {
    store.dispatch(deleteTodo(targetTodo));
  }

  return (
    <div className="mt-4 grid gap-4 overflow-auto max-h-80">
      {todos &&
        todos.map((todo: Todo) => (
          <div
            className="flex bg-white rounded-lg p-2 w-80 break-all"
            key={todo.id}
          >
            <div>{todo.content}</div>
            <input
              className="ml-auto p-2 max-h-fit rounded-lg bg-red-500 hover:bg-red-600 cursor-pointer"
              type="button"
              value="Delete"
              onClick={() => handleClick(todo)}
            />
          </div>
        ))}
    </div>
  );
}
