// next-todo-list/src/components/AddTodoForm.tsx
"use client";
import { Todo } from "@/app/page";
import { useRef } from "react";

interface AddTodoFormProps {
  todos: Todo[];
  setTodos: React.Dispatch<React.SetStateAction<Todo[]>>;
}

export function AddTodoForm({ todos, setTodos }: AddTodoFormProps) {
  const todoInputRef = useRef<HTMLInputElement>(null);

  function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    if (todoInputRef.current?.value.trim().length === 0) return;

    if (todoInputRef.current === null) return;
    const newTodo = { content: todoInputRef.current.value };
    setTodos([...todos, newTodo]);
    todoInputRef.current.value = "";
  }

  return (
    <form className="flex gap-2" onSubmit={handleSubmit}>
      <input className="bg-white" type="text" ref={todoInputRef} />
      <button className="bg-black text-white hover:bg-neutral-900">
        Add Todo
      </button>
    </form>
  );
}

// svelte-todo-list/src/lib/AddTodoForm.svelte
<script lang="ts">
  import type { Todo } from "../App.svelte";

  interface Props {
    todos: Todo[];
  }

  const { todos }: Props = $props();

  let todoInput: HTMLInputElement | null = null;

  function addTodo(e: Event): void {
    e.preventDefault();

    if (todoInput!.value.trim().length <= 0) return;

    todos.push({ content: todoInput!.value });

    todoInput!.value = "";
  }
</script>

<form class="flex gap-2">
  <input
    class="bg-white p-1 text-black"
    id="todo-input"
    type="text"
    placeholder="Enter your todo text"
    bind:this={todoInput}
  />
  <button
    class="bg-orange-400 hover:bg-orange-500"
    type="submit"
    onclick={addTodo}
  >
    Add Todo
  </button>
</form>
