// redux-todo-list/src/components/AddTodoForm.tsx
import { useRef } from "react";
import { addTodo, incrementLastTodoId, store } from "../store/store";

export function AddTodoForm() {
  const todoInputRef = useRef<HTMLInputElement>(null);

  function handleSubmit(e: React.FormEvent<HTMLFormElement>): void {
    e.preventDefault();
    store.dispatch(incrementLastTodoId());
    const { lastTodoId } = store.getState();

    const todoInputValue = todoInputRef.current!.value;
    if (todoInputValue!.trim().length === 0) return;

    const newTodo = { id: lastTodoId, content: todoInputValue };
    store.dispatch(addTodo(newTodo));
    todoInputRef.current!.value = "";
  }

  return (
    <form className="flex gap-4" onSubmit={handleSubmit}>
      <input
        className="bg-white rounded-md px-2 py-2"
        type="text"
        ref={todoInputRef}
      />
      <input
        className="bg-blue-500 rounded-md px-2 cursor-pointer hover:bg-blue-600"
        type="submit"
        value="Add Todo"
      />
    </form>
  );
}

// svelte-todo-list/src/lib/AddTodoForm.svelte
<script lang="ts">
  import type { Todo } from "../App.svelte";

  interface Props {
    todos: Todo[];
  }

  const { todos }: Props = $props();

  let todoInput: HTMLInputElement | null = null;

  function addTodo(e: Event): void {
    e.preventDefault();

    if (todoInput!.value.trim().length <= 0) return;

    todos.push({ content: todoInput!.value });

    todoInput!.value = "";
  }
</script>

<form class="flex gap-2">
  <input
    class="bg-white p-1 text-black"
    id="todo-input"
    type="text"
    placeholder="Enter your todo text"
    bind:this={todoInput}
  />
  <button
    class="bg-orange-400 hover:bg-orange-500"
    type="submit"
    onclick={addTodo}
  >
    Add Todo
  </button>
</form>
