// svelte-todo-list/src/App.svelte
<script lang="ts">
  let todoInput: HTMLInputElement | null = null;

  interface Todo {
    content: string;
  }

  let todos: Todo[] = $state([]);

  function addTodo(e: Event) {
    e.preventDefault();

    if (todoInput!.value.trim().length <= 0) return;

    todos.push({ content: todoInput!.value });

    todoInput!.value = "";
  }

  function deleteTodo(targetTodo: Todo) {
    todos = todos.filter((todo) => todo !== targetTodo);
  }
</script>

<main class="flex h-screen justify-center bg-gray-500">
  <div class="flex flex-col gap-4 text-center">
    <h1 class="mt-40 text-3xl">Svelte Todo List</h1>
    <form>
      <input
        class="bg-white p-1 text-black"
        id="todo-input"
        type="text"
        placeholder="Enter your todo text"
        bind:this={todoInput}
      />
      <button
        class="bg-orange-400 hover:bg-orange-500"
        type="submit"
        onclick={addTodo}
      >
        Add Todo
      </button>
    </form>
    <div class="grid gap-2">
      {#each todos as todo}
        <div
          class="flex w-80 items-center justify-between gap-2 rounded-lg bg-white p-2"
        >
          <div class="text-start break-all">{todo.content}</div>
          <button
            class="self-start bg-red-500 whitespace-nowrap hover:bg-red-600"
            onclick={() => deleteTodo(todo)}
          >
            Delete
          </button>
        </div>
      {/each}
    </div>
  </div>
</main>

// react-todo-list/src/App.jsx
import { useRef, useState } from "react";

export default function App() {
  const [lastTodoId, setLastTodoId] = useState(0);
  const [todos, setTodos] = useState([]);
  const todoInputRef = useRef(null);

  function handleClick(e) {
    e.preventDefault();
    setLastTodoId((prevId) => prevId + 1);

    const todoInputValue = todoInputRef.current.value;
    if (todoInputValue.trim().length > 0) {
      setTodos([...todos, { id: lastTodoId, content: todoInputValue }]);
      todoInputRef.current.value = "";
    }
  }

  function deleteTodo(targetTodo) {
    setTodos([...todos.filter((todo) => todo !== targetTodo)]);
  }

  return (
    <div className="h-screen bg-gray-700">
      <div className="flex flex-col justify-center items-center pt-50">
        <form className="flex gap-4">
          <input
            className="bg-white rounded-md px-2 py-2"
            type="text"
            ref={todoInputRef}
          />
          <input
            className="bg-gray-200 rounded-md px-2 cursor-pointer hover:bg-gray-400"
            type="submit"
            value="Add Todo"
            onClick={handleClick}
          />
        </form>
        <div className="mt-4 grid gap-4 overflow-auto max-h-80">
          {todos &&
            todos.map((todo) => (
              <div
                className="flex bg-white rounded-lg p-2 w-100 break-all"
                key={todo.id}
              >
                <div>{todo.content}</div>
                <input
                  className="ml-auto p-2 max-h-fit bg-red-500 hover:bg-red-600 cursor-pointer"
                  type="button"
                  value="Delete Todo"
                  onClick={() => deleteTodo(todo)}
                />
              </div>
            ))}
        </div>
      </div>
    </div>
  );
}
